### ISSUE TITLE
Lyckas inte logga in

### ISSUE THREAD

**Issue by welandfr** [CNA-22/scalperz-store#27]
Får följande error: 

Uncaught (in promise) TypeError: e.response is undefined
    onClick Login.js:28
    promise callback*onClick Login.js:26
    React 11
    unstable_runWithPriority scheduler.production.min.js:18
    React 11
    <anonymous> index.js:6
    <anonymous> index.js:8
    <anonymous> index.js:8
[main.d7afcdd7.js:2:385584](https://scalperz-store.herokuapp.com/static/js/main.d7afcdd7.js)

**Comment by FrediWa** [comment]
Var loggar du in och med vad? Både live sidan och lokalt (fresh clone) funkar för mig utan problem. Med andra ord, kan inte återskapa problemet.

**Comment by welandfr** [comment]
Kan du komma till Discord?

**Comment by FrediWa** [comment]
Errorn uppkommer på Firefox 97.0.1 men fungerar på Chrome 98.0.4758.102

**Comment by FrediWa** [comment]
Fixed
